import{links,subjects,defaultTasks}from"./data.js";
const app=document.querySelector("#app");
const state={tasks:JSON.parse(localStorage.getItem("snipex_tasks")||"null")||defaultTasks};
const save=()=>localStorage.setItem("snipex_tasks",JSON.stringify(state.tasks));
const bar=v=>`<div class="progress"><span style="width:${v}%"></span></div>`;
const card=(title,body,action="")=>`<article class="card"><div class="card-head"><h2>${title}</h2>${action}</div>${body}</article>`;
function shell(content,active="home"){app.innerHTML=`<div class="app-shell"><header class="topbar"><button class="brand" onclick="dashboard()"><span class="brand-mark">S</span><span><b>SNIPEX</b><small>Personal Command Center</small></span></button><button class="icon-btn" onclick="morePage()">☰</button></header><main class="content">${content}</main><nav class="bottom-nav"><button class="nav-item ${active==="home"?"active":""}" onclick="dashboard()">⌂<small>Home</small></button><button class="nav-item ${active==="links"?"active":""}" onclick="linksPage()">⌁<small>Links</small></button><button class="add-btn" onclick="addFeature()">+</button><button class="nav-item ${active==="tasks"?"active":""}" onclick="tasksPage()">✓<small>Tasks</small></button><button class="nav-item ${active==="more"?"active":""}" onclick="morePage()">•••<small>More</small></button></nav></div>`;}
function dashboard(){const done=state.tasks.filter(t=>t.done).length;shell(`<section class="hero"><p class="eyebrow">PERSONAL COMMAND CENTER</p><h1>Good morning, Snipex.</h1><p class="muted">Your dashboard. Your systems. Your progress.</p></section><button class="search" onclick="openSearch()">⌕ <span>Search anything...</span><kbd>Ctrl K</kbd></button><section class="section"><div class="section-head"><h2>Quick Access</h2><button onclick="linksPage()">View all →</button></div><div class="link-grid">${links.slice(0,4).map(l=>`<a class="link-card" href="${l[1]}"><span class="icon">${l[2]}</span><b>${l[0]}</b><small>Open link</small></a>`).join("")}</div></section><div class="grid two">${card("▣ My PC",`<h3>Pentium G2030</h3><p class="muted">3.00 GHz • 4 GB DDR3</p><div class="mini-stats"><span>500 GB HDD</span><span>Intel HD</span></div><button class="outline" onclick="pcPage()">View details →</button>`)}${card("▤ Academics",`<div class="overall">78%<span>Overall progress</span></div>${subjects.slice(0,3).map(s=>`<div class="subject-mini"><div><span>${s[0]}</span><b>${s[1]}%</b></div>${bar(s[1])}</div>`).join("")}`)}</div><div class="grid two">${card("● DigiGold",`<div class="big-value">₹ —</div><p class="muted">Current value</p><div class="mini-stats"><span>Invested ₹ —</span><span>Gain —</span></div><button class="outline" onclick="goldPage()">View tracker →</button>`)}${card("✓ Weekly Tasks",`<div class="big-value">${done}/${state.tasks.length}</div><p class="muted">completed</p>${bar(Math.round(done/state.tasks.length*100))}<button class="outline" onclick="tasksPage()">View tasks →</button>`)}</div><button class="server-card" onclick="minecraftPage()"><div class="server-art">⛏</div><div><p class="eyebrow">VOIDREIGN MINECRAFT</p><h2>Coming Soon</h2><p class="muted">Server monitoring will appear here.</p></div><span class="badge">COMING SOON</span></button>`);}
function linksPage(){shell(`<div class="page-head"><button onclick="dashboard()">←</button><h1>Quick Access</h1><button onclick="addLink()">＋ Add</button></div><div class="chips"><button class="chip active">All</button></div><div class="link-grid large">${links.map(l=>`<a class="link-card" href="${l[1]}"><span class="icon">${l[2]}</span><b>${l[0]}</b><small>Open link →</small></a>`).join("")}</div>`,"links");}
function pcPage(){shell(`<div class="page-head"><button onclick="dashboard()">←</button><h1>My PC</h1></div>${card("Intel Pentium G2030",'<p class="muted">Still in use. Still gets the job done.</p>')}${card("Specifications",["CPU|Intel Pentium G2030 • 3.00 GHz","RAM|4 GB DDR3 • 1333 MHz","Storage|500 GB HDD","Graphics|Intel HD Graphics","Motherboard|PIH61T","OS|Windows 10 Home • 22H2"].map(x=>{const[a,b]=x.split("|");return`<div class="detail-row"><span>${a}</span><b>${b}</b></div>`}).join(""))}`);}
function academicsPage(){shell(`<div class="page-head"><button onclick="dashboard()">←</button><h1>Academics</h1></div>${card("Overall",`<div class="overall big">78%<span>Overall progress</span></div>${subjects.map(s=>`<div class="subject"><div><span>◈ ${s[0]}</span><b>${s[1]}%</b></div>${bar(s[1])}</div>`).join("")}`)}${card("Weak Areas","<p>• Banking</p><p>• Shares & Dividends</p><p>• Probability</p>")}`);}
function tasksPage(){const done=state.tasks.filter(t=>t.done).length;shell(`<div class="page-head"><button onclick="dashboard()">←</button><div><h1>Weekly Tasks</h1><p class="muted">${done}/${state.tasks.length} completed</p></div><button onclick="addTask()">＋</button></div><div class="task-progress">${bar(Math.round(done/state.tasks.length*100))}</div><div class="task-list">${state.tasks.map(t=>`<label class="task ${t.done?"done":""}"><input type="checkbox" ${t.done?"checked":""} onchange="toggleTask(${t.id})"><span>${t.title}</span><em class="${t.priority}">${t.priority}</em></label>`).join("")}</div>`,"tasks");}
function goldPage(){shell(`<div class="page-head"><button onclick="dashboard()">←</button><h1>DigiGold</h1></div>${card("● DigiGold",'<p class="muted">Track your digital gold investment</p>')}${card("Tracker",["Current Value","Invested","Quantity","Profit / Loss","Last Updated"].map(x=>`<div class="detail-row"><span>${x}</span><b>—</b></div>`).join(""))}<p class="notice">No FamPay credentials are stored here. Connect an authorized data source or manual entry later.</p>`);}
function minecraftPage(){shell(`<div class="page-head"><button onclick="dashboard()">←</button><h1>VoidReign</h1></div><div class="server-art big-art">⛏<b>VOIDREIGN</b><span>COMING SOON</span></div>${card("Server Status",["Status|Coming Soon","Players|—","Version|—","Location|—"].map(x=>{const[a,b]=x.split("|");return`<div class="detail-row"><span>${a}</span><b>${b}</b></div>`}).join(""))}`);}
function morePage(){shell(`<div class="page-head"><h1>More</h1></div><div class="menu-list">${[["⌘","My PC",pcPage],["◈","Academics",academicsPage],["●","DigiGold",goldPage],["⛏","Minecraft",minecraftPage],["⚙","Settings",settingsPage]].map(x=>`<button onclick="(${x[2].name})()"><span class="icon">${x[0]}</span><span>${x[1]}</span><b>›</b></button>`).join("")}</div>`,"more");}
function settingsPage(){shell(`<div class="page-head"><button onclick="dashboard()">←</button><h1>Settings</h1></div>${card("Appearance",'<div class="setting"><span>Darkstar theme</span><b>ON</b></div><div class="setting"><span>Purple accent</span><b>●</b></div>')}${card("Dashboard",["My PC","Academics","Weekly Tasks","DigiGold","Minecraft"].map(x=>`<div class="setting"><span>${x}</span><input type="checkbox" checked></div>`).join(""))}`,"more");}
function addTask(){const title=prompt("Task name");if(title){state.tasks.push({id:Date.now(),title,done:false,priority:"medium"});save();tasksPage();}}
function toggleTask(id){const t=state.tasks.find(x=>x.id===id);t.done=!t.done;save();tasksPage();}
function addLink(){const name=prompt("Link name"),url=prompt("URL");if(name&&url)alert("Add-link storage can be upgraded to persistent settings next.");}
function addFeature(){alert("Feature launcher ready — add Notes, Calendar, Expense Tracker, Study Timer, Weather and more as modules.");}
function openSearch(){const q=prompt("Search dashboard");if(q)alert("Search index upgrade ready for the next iteration.");}
document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();openSearch();}});
window.dashboard=dashboard;window.linksPage=linksPage;window.pcPage=pcPage;window.academicsPage=academicsPage;window.tasksPage=tasksPage;window.goldPage=goldPage;window.minecraftPage=minecraftPage;window.morePage=morePage;window.settingsPage=settingsPage;window.addTask=addTask;window.toggleTask=toggleTask;window.addLink=addLink;window.addFeature=addFeature;window.openSearch=openSearch;
dashboard();