import{links as seedLinks,subjects,defaultTasks,featureDefaults}from"./data.js";
const app=document.querySelector("#app");
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const state={links:read("snipex_links",seedLinks),tasks:read("snipex_tasks",defaultTasks),features:read("snipex_features",featureDefaults)};
const save=()=>{localStorage.setItem("snipex_tasks",JSON.stringify(state.tasks));localStorage.setItem("snipex_links",JSON.stringify(state.links));localStorage.setItem("snipex_features",JSON.stringify(state.features));};
const esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const validUrl=u=>/^https?:\/\//i.test(u);
const icon=n=>({search:"⌕",menu:"☰",home:"⌂",link:"↗",monitor:"▣",book:"▤",check:"✓",gold:"◉",pickaxe:"⛏",settings:"⚙",github:"◈",drive:"◆",school:"▣",youtube:"▶",discord:"◉",minecraft:"⛏",trash:"⌫"}[n]||"•");
const bar=v=>`<div class="progress"><span style="width:${v}%"></span></div>`;
const card=(title,body,action="")=>`<article class="card"><div class="card-head"><h2>${title}</h2>${action}</div>${body}</article>`;
function shell(content,active="home"){app.innerHTML=`<div class="app-shell"><header class="topbar"><button class="brand" data-action="dashboard"><span class="brand-mark">S</span><span><b>SNIPEX</b><small>Personal Command Center</small></span></button><button class="icon-btn" data-action="more">${icon("menu")}</button></header><main class="content">${content}</main><nav class="bottom-nav"><button class="nav-item ${active==="home"?"active":""}" data-action="dashboard">${icon("home")}<small>Home</small></button><button class="nav-item ${active==="links"?"active":""}" data-action="links">${icon("link")}<small>Links</small></button><button class="add-btn" data-action="add-feature">+</button><button class="nav-item ${active==="tasks"?"active":""}" data-action="tasks">${icon("check")}<small>Tasks</small></button><button class="nav-item ${active==="more"?"active":""}" data-action="more">${icon("menu")}<small>More</small></button></nav></div>`;}
function linkCard(l){const target=validUrl(l.url)?`href="${esc(l.url)}" target="_blank" rel="noopener noreferrer"`:`href="#" data-action="edit-link" data-id="${esc(l.id)}"`;return `<a class="link-card" ${target}><span class="icon">${icon(l.icon)}</span><b>${esc(l.name)}</b><small>${validUrl(l.url)?"Open link":"Set URL →"}</small></a>`;}
function dashboard(){const done=state.tasks.filter(t=>t.done).length;const enabled=id=>state.features.find(f=>f.id===id)?.enabled!==false;shell(`<section class="hero"><p class="eyebrow">PERSONAL COMMAND CENTER</p><h1>Good morning, Snipex.</h1><p class="muted">Your dashboard. Your systems. Your progress.</p></section><button class="search" data-action="search"><span>${icon("search")}</span><span>Search anything...</span><kbd>Ctrl K</kbd></button><section class="section"><div class="section-head"><h2>Quick Access</h2><button data-action="links">View all →</button></div><div class="link-grid">${state.links.slice(0,4).map(linkCard).join("")}</div></section><div class="grid two">${enabled("pc")?card("▣ My PC",`<h3>Pentium G2030</h3><p class="muted">3.00 GHz • 4 GB DDR3</p><div class="mini-stats"><span>500 GB HDD</span><span>Intel HD</span></div><button class="outline" data-action="pc">View details →</button>`):""}${enabled("academics")?card("▤ Academics",`<div class="overall">78%<span>Overall progress</span></div>${subjects.slice(0,3).map(s=>`<div class="subject-mini"><div><span>${esc(s.name)}</span><b>${s.value}%</b></div>${bar(s.value)}</div>`).join("")}<button class="outline" data-action="academics">View academics →</button>`):""}</div><div class="grid two">${enabled("digigold")?card("◉ DigiGold",`<div class="big-value">₹ —</div><p class="muted">Current value</p><div class="mini-stats"><span>Invested ₹ —</span><span>Gain —</span></div><button class="outline" data-action="gold">Open tracker →</button>`):""}${enabled("tasks")?card("✓ Weekly Tasks",`<div class="big-value">${done}/${state.tasks.length}</div><p class="muted">completed</p>${bar(state.tasks.length?Math.round(done/state.tasks.length*100):0)}<button class="outline" data-action="tasks">View tasks →</button>`):""}</div>${enabled("minecraft")?`<button class="server-card" data-action="minecraft"><div class="server-art">⛏</div><div><p class="eyebrow">VOIDREIGN MINECRAFT</p><h2>Coming Soon</h2><p class="muted">Server monitoring will appear here.</p></div><span class="badge">COMING SOON</span></button>`:""}`);}
function linksPage(){shell(`<div class="page-head"><button data-action="dashboard">←</button><h1>Quick Access</h1><button data-action="add-link">＋ Add</button></div><div class="chips"><span class="chip active">All ${state.links.length}</span></div><div class="link-grid large">${state.links.map(linkCard).join("")}</div>`,"links");}
function pcPage(){shell(`<div class="page-head"><button onclick="dashboard()">←</button><h1>My PC</h1></div>${card("Intel Pentium G2030",'<p class="muted">Still in use. Still gets the job done.</p>')}${card("Specifications",["CPU|Intel Pentium G2030 • 3.00 GHz","RAM|4 GB DDR3 • 1333 MHz","Storage|500 GB HDD","Graphics|Intel HD Graphics","Motherboard|PIH61T","OS|Windows 10 Home • 22H2"].map(x=>{const[a,b]=x.split("|");return`<div class="detail-row"><span>${a}</span><b>${b}</b></div>`}).join(""))}`);}
function academicsPage(){shell(`<div class="page-head"><button data-action="dashboard">←</button><h1>Academics</h1></div>${card("Overall",`<div class="overall big">78%<span>Overall progress</span></div>${subjects.map(s=>`<div class="subject"><div><span>${esc(s.name)}</span><b>${s.value}%</b></div>${bar(s.value)}</div>`).join("")}`)}${card("Weak Areas","<p>• Banking</p><p>• Shares & Dividends</p><p>• Probability</p>")}`);}
function tasksPage(){const done=state.tasks.filter(t=>t.done).length;shell(`<div class="page-head"><button onclick="dashboard()">←</button><div><h1>Weekly Tasks</h1><p class="muted">${done}/${state.tasks.length} completed</p></div><button onclick="addTask()">＋</button></div><div class="task-progress">${bar(Math.round(done/state.tasks.length*100))}</div><div class="task-list">${state.tasks.map(t=>`<label class="task ${t.done?"done":""}"><input type="checkbox" ${t.done?"checked":""} onchange="toggleTask(${t.id})"><span>${t.title}</span><em class="${t.priority}">${t.priority}</em></label>`).join("")}</div>`,"tasks");}
function goldPage(){shell(`<div class="page-head"><button onclick="dashboard()">←</button><h1>DigiGold</h1></div>${card("● DigiGold",'<p class="muted">Track your digital gold investment</p>')}${card("Tracker",["Current Value","Invested","Quantity","Profit / Loss","Last Updated"].map(x=>`<div class="detail-row"><span>${x}</span><b>—</b></div>`).join(""))}<p class="notice">No FamPay credentials are stored here. Connect an authorized data source or manual entry later.</p>`);}
function minecraftPage(){shell(`<div class="page-head"><button onclick="dashboard()">←</button><h1>VoidReign</h1></div><div class="server-art big-art">⛏<b>VOIDREIGN</b><span>COMING SOON</span></div>${card("Server Status",["Status|Coming Soon","Players|—","Version|—","Location|—"].map(x=>{const[a,b]=x.split("|");return`<div class="detail-row"><span>${a}</span><b>${b}</b></div>`}).join(""))}`);}
function morePage(){shell(`<div class="page-head"><h1>More</h1></div><div class="menu-list">${[["⌘","My PC",pcPage],["◈","Academics",academicsPage],["●","DigiGold",goldPage],["⛏","Minecraft",minecraftPage],["⚙","Settings",settingsPage]].map(x=>`<button onclick="(${x[2].name})()"><span class="icon">${x[0]}</span><span>${x[1]}</span><b>›</b></button>`).join("")}</div>`,"more");}
function settingsPage(){shell(`<div class="page-head"><button data-action="more">←</button><h1>Settings</h1></div>${card("Dashboard modules",state.features.map(f=>`<label class="setting"><span>${esc(f.name)}</span><input type="checkbox" data-feature-toggle="${f.id}" ${f.enabled?"checked":""}></label>`).join(""))}${card("Data",'<button class="outline" data-action="export">Export data</button><button class="outline" data-action="reset" style="margin-top:8px">Reset local data</button>')}`,"more");}
function addTask(){const title=prompt("Task name");if(title?.trim()){state.tasks.push({id:Date.now(),title:title.trim(),done:false,priority:"medium"});save();tasksPage();}}
function toggleTask(id){const t=state.tasks.find(x=>x.id===id);if(t){t.done=!t.done;save();tasksPage();}}
function addLink(){const name=prompt("Link name");const url=prompt("URL (https://...)");if(!name||!url)return;if(!validUrl(url)){alert("Please enter a valid http(s) URL.");return}state.links.push({id:"link-"+Date.now(),name:name.trim(),url:url.trim(),icon:"link",desc:"Custom link"});save();linksPage();}
function addFeature(){morePage();}
function openSearch(){const q=prompt("Search links, tasks or pages");if(!q)return;const needle=q.toLowerCase();const hits=[...state.links.map(x=>"Link: "+x.name),...state.tasks.map(x=>"Task: "+x.title),"Page: My PC","Page: Academics","Page: DigiGold","Page: VoidReign","Page: Settings"].filter(x=>x.toLowerCase().includes(needle));alert(hits.length?hits.slice(0,8).join("\\n"):"No results found.");}
app.addEventListener("click",e=>{const btn=e.target.closest("[data-action]");if(!btn)return;const a=btn.dataset.action;if(a==="edit-link"){e.preventDefault();const l=state.links.find(x=>x.id===btn.dataset.id);if(l){const url=prompt("Set URL for "+l.name,l.url||"https://");if(url&&validUrl(url)){l.url=url.trim();save();linksPage();}else if(url){alert("Please enter a valid http(s) URL.");}}return}const map={dashboard,links:linksPage,pc:pcPage,academics:academicsPage,tasks:tasksPage,gold:goldPage,minecraft:minecraftPage,more:morePage,settings:settingsPage,"add-task":addTask,"add-link":addLink,"add-feature":addFeature,search:openSearch,export:()=>{const blob=new Blob([JSON.stringify({links:state.links,tasks:state.tasks,features:state.features},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="snipex-backup.json";a.click();},"reset":()=>{if(confirm("Reset saved dashboard data?")){localStorage.clear();location.reload();}}};if(map[a]){e.preventDefault();map[a]();}});
app.addEventListener("change",e=>{if(e.target.matches("[data-feature-toggle]")){const f=state.features.find(x=>x.id===e.target.dataset.featureToggle);if(f){f.enabled=e.target.checked;save();dashboard();}}});
document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();openSearch();}});
window.dashboard=dashboard;window.linksPage=linksPage;window.pcPage=pcPage;window.academicsPage=academicsPage;window.tasksPage=tasksPage;window.goldPage=goldPage;window.minecraftPage=minecraftPage;window.morePage=morePage;window.settingsPage=settingsPage;window.addTask=addTask;window.toggleTask=toggleTask;window.addLink=addLink;window.addFeature=addFeature;window.openSearch=openSearch;
dashboard();