import{links as seedLinks,subjects as seedSubjects,defaultTasks,featureDefaults}from"./data.js";
const root=document.querySelector("#app");
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}};
const state={links:read("snipex_links",seedLinks),tasks:read("snipex_tasks",defaultTasks),features:read("snipex_features",featureDefaults),subjects:read("snipex_subjects",seedSubjects),gold:read("snipex_gold",{invested:0,quantity:0,current:0})};
const save=()=>{Object.entries({snipex_links:state.links,snipex_tasks:state.tasks,snipex_features:state.features,snipex_subjects:state.subjects,snipex_gold:state.gold}).forEach(([k,v])=>localStorage.setItem(k,JSON.stringify(v)))};
const esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const urlOk=u=>/^https?:\/\//i.test(u);
const icons={home:'<svg viewBox="0 0 24 24"><path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z"/></svg>',link:'<svg viewBox="0 0 24 24"><path d="M10 13a5 5 0 0 0 7.1.1l2-2a5 5 0 0 0-7.1-7.1l-1.1 1.1"/><path d="M14 11a5 5 0 0 0-7.1-.1l-2 2A5 5 0 0 0 12 20l1.1-1.1"/></svg>',search:'<svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg>',monitor:'<svg viewBox="0 0 24 24"><rect x="3" y="4" width="18" height="13" rx="2"/><path d="M8 21h8M12 17v4"/></svg>',book:'<svg viewBox="0 0 24 24"><path d="M4 5.5A2.5 2.5 0 0 1 6.5 3H20v16H6.5A2.5 2.5 0 0 0 4 21.5z"/><path d="M4 5.5v16"/></svg>',check:'<svg viewBox="0 0 24 24"><path d="m5 12 4 4L19 6"/></svg>',gold:'<svg viewBox="0 0 24 24"><path d="M12 3 21 8l-9 5-9-5z"/><path d="m3 8 9 5 9-5M5 12v5l7 4 7-4v-5"/></svg>',pickaxe:'<svg viewBox="0 0 24 24"><path d="m14 4 6 6M4 20 16 8M3 7l4-4 5 5-4 4z"/></svg>',settings:'<svg viewBox="0 0 24 24"><path d="M12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7z"/><path d="m19.4 15 .1.1-1.8 3.1-.2-.1a2 2 0 0 0-2 .2l-.2.1a2 2 0 0 0-.9 1.7v.2h-3.6v-.2a2 2 0 0 0-.9-1.7l-.2-.1a2 2 0 0 0-2-.2l-.2.1-1.8-3.1.1-.1a2 2 0 0 0 .7-1.9v-.2a2 2 0 0 0-1.4-1.5l-.2-.1V7.7l.2-.1a2 2 0 0 0 1.4-1.5v-.2A2 2 0 0 0 5.8 4l-.1-.1L7.5.8l.2.1a2 2 0 0 0 2-.2l.2-.1A2 2 0 0 0 10.8 0h3.6v.6a2 2 0 0 0 .9 1.7l.2.1a2 2 0 0 0 2 .2l.2-.1L19.5 5l-.1.1a2 2 0 0 0-.7 1.9v.2a2 2 0 0 0 1.4 1.5l.2.1v3.6l-.2.1a2 2 0 0 0-1.4 1.5v.2a2 2 0 0 0 .7.8z"/></svg>',github:'<svg viewBox="0 0 24 24"><path d="M9 19c-4 1.5-4-2-5.5-2M15 19v-3.5a3.5 3.5 0 0 0-1-2.7c3.3-.4 6.8-1.6 6.8-7A5.5 5.5 0 0 0 19.3 2 5.1 5.1 0 0 0 19.2 0S17.8-.4 15 1.4a13.4 13.4 0 0 0-6 0C6.2-.4 4.8 0 4.8 0a5.1 5.1 0 0 0-.1 2A5.5 5.5 0 0 0 3.2 5.8c0 5.4 3.5 6.6 6.8 7a3.5 3.5 0 0 0-1 2.7V19"/></svg>',youtube:'<svg viewBox="0 0 24 24"><path d="M22 12s0-4-1-5-4-1-9-1-8 0-9 1-1 5-1 5 0 4 1 5 4 1 9 1 8 0 9-1 1-5 1-5z"/><path d="m10 9 5 3-5 3z"/></svg>',drive:'<svg viewBox="0 0 24 24"><path d="m8 3 4 7H4zM16 3l4 7h-8zM4 10h16l-4 7H8zM8 17h8l-4 4z"/></svg>',school:'<svg viewBox="0 0 24 24"><path d="m3 9 9-5 9 5-9 5zM6 11v5c3 2 9 2 12 0v-5M21 9v7"/></svg>',discord:'<svg viewBox="0 0 24 24"><path d="M19 5.5A16 16 0 0 0 15.5 4l-.5 1a14 14 0 0 0-6 0L8.5 4A16 16 0 0 0 5 5.5C3.5 7.8 3 10 3.2 14c2 1.5 4 2.2 6 2.5l1-1.2c-.7-.2-1.3-.5-1.8-.8 1.6.7 4.6 1 7.2 0-.5.3-1.1.6-1.8.8l1 1.2c2-.3 4-1 6-2.5.2-4-.3-6.2-1.8-8.5zM8.5 12.5a1.3 1.3 0 1 1 0-2.6 1.3 1.3 0 0 1 0 2.6zm7 0a1.3 1.3 0 1 1 0-2.6 1.3 1.3 0 0 1 0 2.6z"/></svg>'};
const ico=n=>icons[n]||icons.link;
const bar=v=>`<div class="progress"><span style="width:${Math.max(0,Math.min(100,v))}%"></span></div>`;
const card=(title,body)=>`<article class="card"><div class="card-head"><h2>${title}</h2></div>${body}</article>`;
function shell(content,active="home"){root.innerHTML=`<div class="app-shell"><aside class="sidebar"><button class="brand" data-action="dashboard"><span class="brand-mark">S</span><span><b>SNIPEX</b><small>COMMAND CENTER</small></span></button><div class="side-nav">${[['home','Dashboard','dashboard'],['link','Quick Access','links'],['monitor','My PC','pc'],['book','Academics','academics'],['check','Weekly Tasks','tasks'],['gold','DigiGold','gold'],['pickaxe','VoidReign','minecraft']].map(x=>`<button class="${active===x[2]?'active':''}" data-action="${x[2]}">${ico(x[0])}<span>${x[1]}</span></button>`).join("")}</div><button class="settings-link" data-action="settings">${ico("settings")}<span>Settings</span></button></aside><header class="topbar"><button class="brand mobile-brand" data-action="dashboard"><span class="brand-mark">S</span><span><b>SNIPEX</b><small>COMMAND CENTER</small></span></button><button class="mobile-menu" data-action="more">☰</button></header><main class="content">${content}</main><nav class="bottom-nav"><button class="${active==="home"?"active":""}" data-action="dashboard">${ico("home")}<small>Home</small></button><button class="${active==="links"?"active":""}" data-action="links">${ico("link")}<small>Links</small></button><button class="add-btn" data-action="add-link">+</button><button class="${active==="tasks"?"active":""}" data-action="tasks">${ico("check")}<small>Tasks</small></button><button class="${active==="more"?"active":""}" data-action="more">${ico("settings")}<small>More</small></button></nav></div>`;document.querySelectorAll(".icon").forEach(x=>x.innerHTML=ico(x.dataset.icon||"link"))}
function dashboard(){const done=state.tasks.filter(t=>t.done).length;const enabled=id=>state.features.find(f=>f.id===id)?.enabled!==false;shell(`<section class="hero"><p class="eyebrow">PERSONAL COMMAND CENTER</p><h1>Good morning, Snipex.</h1><p class="muted">Your dashboard. Your systems. Your progress.</p></section><button class="search" data-action="search">${ico("search")}<span>Search anything...</span><kbd>Ctrl K</kbd></button><section class="section"><div class="section-head"><h2>Quick Access</h2><button data-action="links">View all →</button></div><div class="link-grid">${state.links.slice(0,4).map(linkCard).join("")}</div></section><div class="grid two">${enabled("pc")?card(`${ico("monitor")} My PC`,`<h3>Pentium G2030</h3><p class="muted">3.00 GHz • 4 GB DDR3</p><div class="mini-stats"><span>500 GB HDD</span><span>Intel HD</span></div><button class="outline" data-action="pc">View details →</button>`):""}${enabled("academics")?card(`${ico("book")} Academics`,`<div class="overall">${Math.round(state.subjects.reduce((a,b)=>a+b.value,0)/state.subjects.length)}%<span>Average progress</span></div>${state.subjects.slice(0,3).map(s=>`<div class="subject-mini"><div><span>${esc(s.name)}</span><b>${s.value}%</b></div>${bar(s.value)}</div>`).join("")}<button class="outline" data-action="academics">View academics →</button>`):""}</div><div class="grid two">${enabled("digigold")?card(`${ico("gold")} DigiGold`,`<div class="big-value">${state.gold.current?"₹"+state.gold.current.toLocaleString("en-IN"):"₹ —"}</div><p class="muted">Current value</p><button class="outline" data-action="gold">Open tracker →</button>`):""}${enabled("tasks")?card(`${ico("check")} Weekly Tasks`,`<div class="big-value">${done}/${state.tasks.length}</div><p class="muted">completed</p>${bar(state.tasks.length?Math.round(done/state.tasks.length*100):0)}<button class="outline" data-action="tasks">View tasks →</button>`):""}</div>${enabled("minecraft")?`<button class="server-card" data-action="minecraft"><div class="server-art">${ico("pickaxe")}</div><div><p class="eyebrow">VOIDREIGN MINECRAFT</p><h2>Coming Soon</h2><p class="muted">Server monitoring will appear here.</p></div><span class="badge">COMING SOON</span></button>`:""}`);}
function linkCard(l){const target=urlOk(l.url)?`href="${esc(l.url)}" target="_blank" rel="noopener noreferrer"`:`href="#" data-action="edit-link" data-id="${esc(l.id)}"`;return`<a class="link-card" ${target}><span class="link-icon">${ico(l.icon)}</span><b>${esc(l.name)}</b><small>${urlOk(l.url)?"Open link":"Set URL"}</small></a>`;}
function linksPage(){shell(`<div class="page-head"><button data-action="dashboard">←</button><h1>Quick Access</h1><button class="primary small" data-action="add-link">+ Add Link</button></div><div class="link-grid large">${state.links.map(linkCard).join("")}</div>`,"links")}
function pcPage(){shell(`<div class="page-head"><button data-action="dashboard">←</button><h1>My PC</h1></div>${card("Intel Pentium G2030",'<p class="muted">Your current Snipex machine.</p>')}${card("Specifications",["CPU|Intel Pentium G2030 • 3.00 GHz","RAM|4 GB DDR3 • 1333 MHz","Storage|500 GB HDD","Graphics|Intel HD Graphics","Motherboard|PIH61T MER","OS|Windows 10 Home • 22H2"].map(row).join(""))}`,"pc")}
function academicsPage(){shell(`<div class="page-head"><button data-action="dashboard">←</button><h1>Academics</h1><button class="primary small" data-action="edit-academics">Edit</button></div>${card("Subject Progress",state.subjects.map(s=>`<div class="subject"><div><span>${esc(s.name)}</span><b>${s.value}%</b></div>${bar(s.value)}</div>`).join(""))}${card("Focus Areas",'<p class="muted">Update these based on your latest school exam analysis.</p><div class="mini-stats"><span>Mathematics</span><span>Physics</span></div>')}`,"academics")}
function tasksPage(){const done=state.tasks.filter(t=>t.done).length;shell(`<div class="page-head"><div><h1>Weekly Tasks</h1><p class="muted">${done}/${state.tasks.length} completed</p></div><button class="primary small" data-action="add-task">+ Add</button></div>${bar(state.tasks.length?Math.round(done/state.tasks.length*100):0)}<div class="task-list">${state.tasks.map(t=>`<label class="task ${t.done?"done":""}"><input type="checkbox" data-task="${t.id}" ${t.done?"checked":""}><span>${esc(t.title)}</span><em class="${esc(t.priority)}">${esc(t.priority)}</em><button type="button" data-delete-task="${t.id}">×</button></label>`).join("")}</div>`,"tasks")}
function goldPage(){shell(`<div class="page-head"><button data-action="dashboard">←</button><h1>DigiGold</h1><button class="primary small" data-action="edit-gold">Edit</button></div>${card("Investment Tracker",row("Invested",state.gold.invested?"₹"+state.gold.invested:"—")+row("Quantity",state.gold.quantity?state.gold.quantity+" g":"—")+row("Current Value",state.gold.current?"₹"+state.gold.current:"—")+row("Profit / Loss",state.gold.current&&state.gold.invested?"₹"+(state.gold.current-state.gold.invested):"—"))}<p class="notice">Manual tracker only. This dashboard does not access your private FamPay account or credentials.</p>`,"gold")}
function minecraftPage(){shell(`<div class="page-head"><button data-action="dashboard">←</button><h1>VoidReign</h1></div><div class="server-art big-art">${ico("pickaxe")}<b>VOIDREIGN</b><span>COMING SOON</span></div>${card("Server Status",row("Status","Coming Soon")+row("Players","—")+row("Version","—"))}`,"minecraft")}
function morePage(){shell(`<div class="page-head"><h1>More</h1></div><div class="menu-list">${[["monitor","My PC","pc"],["book","Academics","academics"],["gold","DigiGold","gold"],["pickaxe","VoidReign","minecraft"],["settings","Settings","settings"]].map(x=>`<button data-action="${x[2]}"><span class="menu-icon">${ico(x[0])}</span><span>${x[1]}</span><b>→</b></button>`).join("")}</div>`,"more")}
function settingsPage(){shell(`<div class="page-head"><button data-action="more">←</button><h1>Settings</h1></div>${card("Dashboard Modules",state.features.map(f=>`<label class="setting"><span>${ico(f.icon)} ${esc(f.name)}</span><input type="checkbox" data-feature="${f.id}" ${f.enabled?"checked":""}></label>`).join(""))}${card("Data",'<button class="outline" data-action="export">Export Backup</button><button class="outline danger" data-action="reset">Reset Local Data</button>')}`,"more")}
function row(a,b){return`<div class="detail-row"><span>${esc(a)}</span><b>${esc(b)}</b></div>`}
function modal(title,body){document.body.insertAdjacentHTML("beforeend",`<div class="modal-backdrop" data-modal><section class="modal"><div class="modal-head"><h2>${title}</h2><button data-close>×</button></div>${body}</section></div>`)}
function closeModal(){document.querySelector("[data-modal]")?.remove()}
function formField(label,name,value,type="text"){return`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" required></label>`}
function addLink(){modal("Add Quick Link",`<form id="link-form" class="modal-form">${formField("Name","name","","text")}${formField("URL","url","https://","url")}<label>Icon<select name="icon"><option value="link">Link</option><option value="github">GitHub</option><option value="drive">Google Drive</option><option value="youtube">YouTube</option><option value="school">School</option><option value="discord">Discord</option></select></label><div class="modal-actions"><button type="button" data-close>Cancel</button><button class="primary" type="submit">Save</button></div></form>`);document.querySelector("#link-form").onsubmit=e=>{e.preventDefault();const d=new FormData(e.target),url=String(d.get("url")).trim();if(!urlOk(url))return alert("Enter a valid http(s) URL.");state.links.push({id:"link-"+Date.now(),name:String(d.get("name")).trim(),url,icon:String(d.get("icon")),desc:"Custom link"});save();closeModal();linksPage()}}
function editLink(id){const l=state.links.find(x=>x.id===id);if(!l)return;modal("Edit Link",`<form id="edit-link-form" class="modal-form">${formField("Name","name",l.name)}${formField("URL","url",l.url||"https://","url")}<div class="modal-actions"><button type="button" data-close>Cancel</button><button class="primary" type="submit">Save</button></div></form>`);document.querySelector("#edit-link-form").onsubmit=e=>{e.preventDefault();const d=new FormData(e.target),url=String(d.get("url")).trim();if(!urlOk(url))return alert("Enter a valid http(s) URL.");l.name=String(d.get("name")).trim();l.url=url;save();closeModal();linksPage()}}
function addTask(){modal("Add Task",`<form id="task-form" class="modal-form">${formField("Task","title","")}<label>Priority<select name="priority"><option>high</option><option selected>medium</option><option>low</option></select></label><div class="modal-actions"><button type="button" data-close>Cancel</button><button class="primary" type="submit">Add Task</button></div></form>`);document.querySelector("#task-form").onsubmit=e=>{e.preventDefault();const d=new FormData(e.target);state.tasks.push({id:Date.now(),title:String(d.get("title")).trim(),done:false,priority:String(d.get("priority"))});save();closeModal();tasksPage()}}
function editAcademics(){modal("Edit Academic Progress",`<form id="academic-form" class="modal-form">${state.subjects.map((s,i)=>formField(s.name,"s"+i,s.value,"number")).join("")}<div class="modal-actions"><button type="button" data-close>Cancel</button><button class="primary" type="submit">Save</button></div></form>`);document.querySelector("#academic-form").onsubmit=e=>{e.preventDefault();const d=new FormData(e.target);state.subjects=state.subjects.map((s,i)=>({...s,value:Math.max(0,Math.min(100,Number(d.get("s"+i))))}));save();closeModal();academicsPage()}}
function editGold(){modal("DigiGold Manual Tracker",`<form id="gold-form" class="modal-form">${formField("Invested amount (₹)","invested",state.gold.invested,"number")}${formField("Quantity (grams)","quantity",state.gold.quantity,"number")}${formField("Current value (₹)","current",state.gold.current,"number")}<div class="modal-actions"><button type="button" data-close>Cancel</button><button class="primary" type="submit">Save</button></div></form>`);document.querySelector("#gold-form").onsubmit=e=>{e.preventDefault();const d=new FormData(e.target);state.gold={invested:Number(d.get("invested")),quantity:Number(d.get("quantity")),current:Number(d.get("current"))};save();closeModal();goldPage()}}
function search(){modal("Search",'<input id="search-input" class="search-input" placeholder="Search links, tasks, pages..." autofocus><div id="results"></div>');const input=document.querySelector("#search-input");const render=()=>{const q=input.value.toLowerCase();const data=[...state.links.map(x=>({type:"Link",name:x.name,action:"links"})),...state.tasks.map(x=>({type:"Task",name:x.title,action:"tasks"})),...["My PC","Academics","DigiGold","VoidReign","Settings"].map((name,i)=>({type:"Page",name,action:["pc","academics","gold","minecraft","settings"][i]}))].filter(x=>x.name.toLowerCase().includes(q));document.querySelector("#results").innerHTML=data.slice(0,12).map(x=>`<button class="result" data-action="${x.action}"><small>${x.type}</small><b>${esc(x.name)}</b>→</button>`).join("")||'<p class="muted">No results.</p>'};input.addEventListener("input",render);render()}
function exportData(){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify({links:state.links,tasks:state.tasks,features:state.features,subjects:state.subjects,gold:state.gold},null,2)],{type:"application/json"}));a.download="snipex-command-center-backup.json";a.click()}
function reset(){if(confirm("Reset all local dashboard data?")){["snipex_links","snipex_tasks","snipex_features","snipex_subjects","snipex_gold"].forEach(localStorage.removeItem.bind(localStorage));location.reload()}}
function navigate(a){({dashboard,links:linksPage,pc:pcPage,academics:academicsPage,tasks:tasksPage,gold:goldPage,minecraft:minecraftPage,more:morePage,settings:settingsPage,"add-link":addLink,"add-task":addTask,search,export:exportData,reset})[a]?.()}
root.addEventListener("click",e=>{const close=e.target.closest("[data-close]");if(close){closeModal();return}const del=e.target.closest("[data-delete-task]");if(del){state.tasks=state.tasks.filter(t=>String(t.id)!==del.dataset.deleteTask);save();tasksPage();return}const btn=e.target.closest("[data-action]");if(btn){e.preventDefault();if(btn.dataset.action==="edit-link")return editLink(btn.dataset.id);navigate(btn.dataset.action)}});
root.addEventListener("change",e=>{if(e.target.matches("[data-task]")){const t=state.tasks.find(x=>String(x.id)===e.target.dataset.task);if(t){t.done=e.target.checked;save();tasksPage()}}if(e.target.matches("[data-feature]")){const f=state.features.find(x=>x.id===e.target.dataset.feature);if(f){f.enabled=e.target.checked;save();dashboard()}}});
document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();search()}if(e.key==="Escape")closeModal()});
dashboard();